apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "balanced.helpers.name" . }}
  labels:
{{ include "balanced.helpers.labels" . | indent 4 }}
spec:
  replicas: {{ default 3 ((.Values.scaling).replicas) }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "balanced.helpers.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "balanced.helpers.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ default (include "balanced.helpers.name" .) ((.Values.image).name) }}
        image: {{ default (include "balanced.helpers.name" .) ((.Values.image).repository) }}:{{ default "latest" ((.Values.image).tag) .Chart.AppVersion }}
        {{- if ((.Values.image).command) }}
        command: {{ ((.Values.image).command) }}
        {{- end }}
        {{- if ((.Values.image).args) }}
        args: {{ ((.Values.image).args) }}
        {{- end }}
        imagePullPolicy: {{ default "IfNotPresent" ((.Values.image).pullPolicy) }}
        envFrom:
        {{- with (.Values.envFromSecret) }}
        {{- toYaml . | nindent 10 }}
        {{- end }}
        env:
        {{- with (.Values.environmentVariables) }}
        {{- tpl (toYaml .) $ | nindent 10 }}
        {{- end }}
        lifecycle:
          {{- if not (.Values.lifecycleDisabled) }}
          preStop:
            exec:
              {{- if (.Values.lifecycleCommand) }}
              command: {{ (.Values.lifecycleCommand) }}
              {{- else }}
              command: ["/bin/sleep", "{{ default 10 (.Values.lifecycleSleepSeconds) }}"]
              {{- end }}
          {{- end }}
        ports:
        - name: {{ default "http" (.Values.portName) }}
          containerPort: {{ default 8080 (.Values.port) }}
          protocol: TCP
        {{- with (.Values.additionalPorts) }}
        {{- toYaml . | nindent 10 }}
        {{- end }}
        resources:
        {{- with (.Values.resources) }}
        {{- toYaml . | nindent 10 }}
        {{- end }}
        volumeMounts:
        {{- with (.Values.volumeMounts) }}
        {{- toYaml . | nindent 10 }}
        {{- end }}
      volumes:
      {{- with (.Values.volumes) }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
      imagePullSecrets:
      {{- if (.Values.imagePullSecret) }}
      - name: {{- (.Values.imagePullSecret) }}
      {{- end }}